type User @key(fields: "id") {
  id:                 ID!
  email:              String
  username:           String
  fullname:           String
  profile_image:      String
  profile_image_url:  String

  created_at:         String
  upadted_at:         String
}

type Query {
  user(id: ID!):      User
}
